# Generated by Django 4.0.1 on 2022-01-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_list',
            name='description',
            field=models.CharField(default='-', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coupon_list',
            name='expiry',
            field=models.DateTimeField(),
        ),
    ]
